import { Platform, StyleSheet } from 'react-native';
import { colors, fonts, radii, shadows, spacing } from '../constants/theme';

export const appStyles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    backgroundColor: Platform.OS === 'web' ? '#0d2b22' : colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneFrame: {
    flex: 1,
    width: '100%',
    maxWidth: 430,
    backgroundColor: colors.background,
    overflow: 'hidden',
    ...(Platform.OS === 'web'
      ? {
          shadowColor: '#000',
          shadowOpacity: 0.45,
          shadowRadius: 50,
          shadowOffset: { width: 0, height: 10 },
        }
      : {}),
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  bgShapeOne: {
    position: 'absolute',
    top: -110,
    right: -20,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: colors.sun,
    opacity: 0.34,
  },
  bgShapeTwo: {
    position: 'absolute',
    bottom: 90,
    left: -80,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: colors.sky,
    opacity: 0.6,
  },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 15,
    marginTop: spacing.md,
  },
  scrollContent: {
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  appHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
    paddingTop: spacing.sm,
  },
  appHeaderTitle: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 22,
  },
  appHeaderSub: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 1,
  },
  headerStats: {
    flexDirection: 'row',
    gap: spacing.sm,
    alignItems: 'center',
  },
  statPill: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statPillDark: {
    backgroundColor: colors.forest,
    borderColor: colors.forest,
  },
  statPillText: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 12,
  },
  statPillTextLight: {
    color: colors.paper,
  },
  workspace: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    ...shadows.soft,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: radii.pill,
    backgroundColor: colors.sky,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.md,
    gap: spacing.xs,
  },
  backArrow: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 16,
  },
  backButtonText: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 14,
  },
});

export const tabBarStyles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    marginBottom: spacing.lg,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.xs,
    ...shadows.soft,
  },
  tab: {
    flex: 1,
    backgroundColor: 'transparent',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  selectedTab: {
    backgroundColor: colors.accentDark,
    ...shadows.soft,
  },
  label: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  selectedLabel: {
    color: colors.paper,
  },
});

export const splashStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.forest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  glowTop: {
    position: 'absolute',
    top: -80,
    right: -60,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: colors.sun,
    opacity: 0.18,
  },
  glowBottom: {
    position: 'absolute',
    bottom: -80,
    left: -60,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: colors.sky,
    opacity: 0.15,
  },
  logoBox: {
    alignItems: 'center',
  },
  iconCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.xl,
  },
  iconEmoji: {
    fontSize: 48,
  },
  appName: {
    color: colors.paper,
    fontFamily: fonts.heading,
    fontSize: 42,
    letterSpacing: 0.5,
  },
  tagline: {
    color: colors.sky,
    fontFamily: fonts.body,
    fontSize: 15,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginTop: spacing.sm,
  },
});

export const welcomeStyles = StyleSheet.create({
  scroll: {
    flexGrow: 1,
    padding: spacing.xl,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xxl,
    backgroundColor: colors.background,
  },
  glowTop: {
    position: 'absolute',
    top: -60,
    right: -30,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: colors.sun,
    opacity: 0.4,
  },
  glowBottom: {
    position: 'absolute',
    bottom: 60,
    left: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: colors.sky,
    opacity: 0.6,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.forest,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    marginBottom: spacing.lg,
  },
  badgeText: {
    color: colors.paper,
    fontFamily: fonts.bodyBold,
    fontSize: 11,
    letterSpacing: 2,
  },
  appName: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 44,
    lineHeight: 50,
    marginBottom: spacing.md,
  },
  tagline: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 16,
    lineHeight: 25,
    marginBottom: spacing.xl,
  },
  sectionLabel: {
    color: colors.forest,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: spacing.sm,
  },
  featureList: {
    gap: spacing.md,
    marginBottom: spacing.xl,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  featureRowPressed: {
    opacity: 0.75,
    backgroundColor: colors.surfaceMuted,
  },
  featureIconBox: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  featureIconText: {
    fontSize: 22,
  },
  featureInfo: {
    flex: 1,
  },
  featureLabel: {
    color: colors.forest,
    fontFamily: fonts.bodyBold,
    fontSize: 15,
  },
  featureDesc: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 13,
    marginTop: 2,
    lineHeight: 18,
  },
  featureArrow: {
    color: colors.muted,
    fontFamily: fonts.bodyBold,
    fontSize: 20,
  },
  hint: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 13,
    textAlign: 'center',
  },
});

export const dayPickerStyles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  chip: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    minWidth: 64,
    alignItems: 'center',
  },
  chipSelected: {
    backgroundColor: colors.accentDark,
    borderColor: colors.accentDark,
  },
  chipCompleted: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  label: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  labelSelected: {
    color: colors.paper,
  },
});

export const filterPanelStyles = StyleSheet.create({
  container: {
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.soft,
  },
  title: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 28,
  },
  caption: {
    color: colors.accentDark,
    fontFamily: fonts.body,
    fontSize: 14,
    marginTop: spacing.sm,
  },
  searchInput: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.ink,
    fontFamily: fonts.body,
    fontSize: 15,
    marginTop: spacing.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  optionGroup: {
    marginTop: spacing.lg,
  },
  optionLabel: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 14,
    marginBottom: spacing.sm,
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  optionChip: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  optionChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  optionText: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  optionTextActive: {
    color: colors.paper,
  },
});

export const paginationStyles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  button: {
    backgroundColor: colors.accentDark,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  buttonDisabled: {
    backgroundColor: colors.surfaceSoft,
  },
  buttonText: {
    color: colors.paper,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  buttonTextDisabled: {
    color: colors.muted,
  },
  pageLabel: {
    color: colors.accentDark,
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.pill,
    overflow: 'hidden',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontFamily: fonts.body,
    fontSize: 13,
  },
});

export const recipeCardStyles = StyleSheet.create({
  wrapper: {
    marginBottom: spacing.md,
    borderRadius: radii.lg,
    overflow: 'hidden',
  },
  swipeBg: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.accentDark,
    borderRadius: radii.lg,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: spacing.xl,
  },
  swipeBgText: {
    color: colors.paper,
    fontFamily: fonts.bodyBold,
    fontSize: 15,
  },
  card: {
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    borderLeftWidth: 5,
    borderLeftColor: colors.accent,
    ...shadows.soft,
  },
  body: {
    gap: spacing.sm,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  badge: {
    backgroundColor: colors.sky,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  badgeText: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 12,
  },
  ratingText: {
    color: colors.accentDark,
    fontFamily: fonts.body,
    fontSize: 12,
  },
  title: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 26,
    lineHeight: 31,
  },
  tagline: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 22,
  },
  factRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  factText: {
    color: colors.ink,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  tag: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  tagText: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
  },
  assignmentText: {
    color: colors.forest,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
    marginTop: spacing.xs,
  },
  assignmentTextMuted: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 13,
    marginTop: spacing.xs,
  },
  quickActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  quickAction: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.accentDark,
    backgroundColor: colors.surfaceSoft,
  },
  quickActionSaved: {
    backgroundColor: colors.accentDark,
  },
  quickActionDismiss: {
    flex: 0,
    paddingHorizontal: spacing.md,
  },
  quickActionText: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  quickActionTextSaved: {
    color: colors.paper,
  },
  saveButton: {
    alignSelf: 'flex-start',
    marginTop: spacing.md,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.accentDark,
    backgroundColor: colors.surfaceSoft,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  saveButtonActive: {
    backgroundColor: colors.accentDark,
    borderColor: colors.accentDark,
  },
  saveLabel: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  saveLabelActive: {
    color: colors.paper,
  },
});

export const favoritesStyles = StyleSheet.create({
  headerCard: {
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    ...shadows.soft,
  },
  title: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 28,
  },
  body: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 23,
    marginTop: spacing.sm,
  },
  statsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  statChip: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    minWidth: 90,
  },
  statValue: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 22,
  },
  statLabel: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 2,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: spacing.xxl,
  },
  emptyTitle: {
    color: colors.ink,
    fontFamily: fonts.heading,
    fontSize: 24,
  },
  emptyBody: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 22,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
});

export const libraryStyles = StyleSheet.create({
  emptyState: {
    alignItems: 'center',
    paddingVertical: spacing.xxl,
  },
  emptyTitle: {
    color: colors.ink,
    fontFamily: fonts.heading,
    fontSize: 24,
  },
  emptyBody: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 15,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
});

export const pantryStyles = StyleSheet.create({
  headerCard: {
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    ...shadows.soft,
  },
  title: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 28,
  },
  body: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 23,
    marginTop: spacing.sm,
  },
  headerStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  headerStat: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  headerValue: {
    color: colors.ink,
    fontFamily: fonts.heading,
    fontSize: 24,
  },
  headerLabel: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
  },
  planButton: {
    alignSelf: 'flex-start',
    borderRadius: radii.pill,
    backgroundColor: colors.accentDark,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginTop: spacing.lg,
  },
  planButtonText: {
    color: colors.paper,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  controlsCard: {
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.soft,
  },
  searchInput: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.ink,
    fontFamily: fonts.body,
    fontSize: 15,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  filterChip: {
    backgroundColor: colors.surfaceSoft,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  filterChipActive: {
    backgroundColor: colors.accent,
  },
  filterLabel: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  filterLabelActive: {
    color: colors.paper,
  },
  listCard: {
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    ...shadows.soft,
  },
  ingredientRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    alignItems: 'center',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  ingredientRowNeeded: {
    borderLeftWidth: 4,
    borderLeftColor: colors.accent,
    paddingLeft: spacing.md,
  },
  ingredientRowStocked: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
  },
  ingredientCopy: {
    flex: 1,
  },
  ingredientName: {
    color: colors.ink,
    fontFamily: fonts.bodyBold,
    fontSize: 15,
  },
  ingredientMeta: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 4,
  },
  ingredientStatus: {
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  ingredientStatusStocked: {
    color: colors.success,
  },
  ingredientStatusMissing: {
    color: colors.danger,
  },
  emptyText: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: spacing.xl,
  },
});

export const planStyles = StyleSheet.create({
  summaryCard: {
    backgroundColor: colors.forest,
    borderRadius: radii.lg,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    ...shadows.soft,
  },
  summaryTitle: {
    color: colors.paper,
    fontFamily: fonts.heading,
    fontSize: 28,
  },
  summaryBody: {
    color: colors.sky,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 23,
    marginTop: spacing.sm,
  },
  metricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  metricTile: {
    backgroundColor: colors.paper,
    borderRadius: radii.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    minWidth: 130,
  },
  metricValue: {
    color: colors.ink,
    fontFamily: fonts.heading,
    fontSize: 24,
  },
  metricLabel: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
  },
  section: {
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.soft,
  },
  sectionTitle: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 24,
  },
  sectionBody: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
    marginTop: spacing.sm,
  },
  dayCard: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingVertical: spacing.lg,
  },
  dayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  dayName: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 16,
  },
  dayMeta: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 13,
  },
  recipeTitle: {
    color: colors.ink,
    fontFamily: fonts.heading,
    fontSize: 22,
    marginTop: spacing.sm,
  },
  recipeMeta: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 14,
    marginTop: spacing.xs,
  },
  emptyDayText: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 14,
    lineHeight: 22,
    marginTop: spacing.sm,
  },
  dayActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  primaryButton: {
    backgroundColor: colors.accentDark,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  primaryButtonText: {
    color: colors.paper,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  secondaryButton: {
    alignSelf: 'flex-start',
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.sun,
    backgroundColor: colors.sun,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginTop: spacing.lg,
  },
  secondaryButtonSmall: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceSoft,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  secondaryButtonText: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  ghostButton: {
    borderRadius: radii.pill,
    backgroundColor: colors.rose,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  ghostButtonText: {
    color: colors.muted,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
  },
  shoppingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  shoppingTextBlock: {
    flex: 1,
  },
  shoppingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    alignItems: 'flex-start',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  shoppingCopy: {
    flex: 1,
  },
  shoppingName: {
    color: colors.ink,
    fontFamily: fonts.bodyBold,
    fontSize: 15,
  },
  shoppingMeta: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 4,
  },
  shoppingRecipes: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 4,
    lineHeight: 18,
  },
  shoppingStatus: {
    color: colors.paper,
    backgroundColor: colors.accent,
    borderRadius: radii.pill,
    overflow: 'hidden',
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    fontFamily: fonts.bodyBold,
    fontSize: 12,
  },
  shoppingStatusMuted: {
    backgroundColor: colors.success,
  },
});

export const recipeDetailStyles = StyleSheet.create({
  hero: {
    backgroundColor: colors.forest,
    borderRadius: radii.lg,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    ...shadows.soft,
  },
  mealType: {
    color: colors.sun,
    fontFamily: fonts.bodyBold,
    fontSize: 13,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
  },
  title: {
    color: colors.paper,
    fontFamily: fonts.heading,
    fontSize: 30,
    lineHeight: 36,
  },
  tagline: {
    color: colors.sky,
    fontFamily: fonts.body,
    fontSize: 16,
    lineHeight: 24,
    marginTop: spacing.md,
  },
  metricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginTop: spacing.xl,
  },
  metricCard: {
    backgroundColor: colors.paper,
    borderRadius: radii.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    minWidth: 92,
  },
  metricValue: {
    color: colors.ink,
    fontFamily: fonts.heading,
    fontSize: 26,
  },
  metricLabel: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xl,
  },
  actionButton: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  primaryAction: {
    backgroundColor: colors.sun,
    borderColor: colors.sun,
  },
  actionText: {
    color: colors.paper,
    fontFamily: fonts.bodyBold,
    fontSize: 14,
  },
  primaryActionText: {
    color: colors.accentDark,
  },
  panel: {
    backgroundColor: colors.paper,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.soft,
  },
  sectionTitle: {
    color: colors.forest,
    fontFamily: fonts.heading,
    fontSize: 24,
  },
  sectionBody: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 22,
    marginTop: spacing.sm,
  },
  assignmentSummary: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 14,
    marginTop: spacing.md,
  },
  listRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    alignItems: 'center',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  listTitle: {
    color: colors.ink,
    fontFamily: fonts.bodyBold,
    fontSize: 15,
  },
  listMeta: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 12,
    marginTop: 2,
  },
  quantity: {
    color: colors.accentDark,
    fontFamily: fonts.bodyBold,
    fontSize: 14,
  },
  stepRow: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  stepNumberBadge: {
    backgroundColor: colors.accent,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepNumber: {
    color: colors.paper,
    fontFamily: fonts.bodyBold,
    fontSize: 14,
  },
  stepText: {
    flex: 1,
    color: colors.ink,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 23,
  },
});
